version: "3"
services:
  jupyterlab_cuda:
    build: .
    container_name: jupyterlab_cuda
    restart: always
    tty: true
    ports:
      - 0.0.0.0:9999:8888
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]